### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bhanu123musetti** [yashshah2609/Emotion-Based-music-player#1]
sir,when iam executing the project in pycharm iam getting these errors can you please explain how to resolve these errors
Traceback (most recent call last):
  File "C:/Users/Bhanu/PycharmProjects/Emotion-Based-music-playerrrr/capture.py", line 15, in <module>
    import eel
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\eel\__init__.py", line 2, in <module>
    import gevent as gvt
  File "C:\Users\Bhanu\AppData\Roaming\Python\Python37\site-packages\gevent\__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "C:\Users\Bhanu\AppData\Roaming\Python\Python37\site-packages\gevent\_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "C:\Users\Bhanu\AppData\Roaming\Python\Python37\site-packages\gevent\_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "C:\Program Files (x86)\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent.__hub_local'

Process finished with exit code 1

**Comment by yashshah2609** [comment]
I think the problem here is with eel library I have uploaded [https://drive.google.com/open?id=1LphmYEBwa-SXbTFXuxIKBAt4iQ1Z2JA8](url) eel library folders here. Just download ( both folder eel and Eel 0.9.10) it and copy paste it in your pc to path : C:\Users\Bhanu\AppData\Roaming\Python\Python37\site-packages\
and then let me know if the same error occure.
Sorry for the late reply.

**Comment by bhanu123musetti** [comment]
thanks for giving reply sir i completed the project successfully
