### ISSUE TITLE
i don't know why?

### ISSUE THREAD

**Issue by starnger** [yashshah2609/Emotion-Based-music-player#4]
when i run capture.py

C:\Users\Mayank\AppData\Local\Programs\Python\Python38-32\python.exe C:/Users/Mayank/PycharmProjects/Emotion-Based-music-player-master/capture.py
Traceback (most recent call last):
  File "C:/Users/Mayank/PycharmProjects/Emotion-Based-music-player-master/capture.py", line 12, in <module>
    import Update_Model
  File "C:\Users\Mayank\PycharmProjects\Emotion-Based-music-player-master\Update_Model.py", line 6, in <module>
    fishface=cv2.face.FisherFaceRecognizer_create()
AttributeError: module 'cv2.cv2' has no attribute 'face'

Process finished with exit code 1

**Comment by starnger** [comment]
Update_Model.py


C:\Users\Mayank\AppData\Local\Programs\Python\Python38-32\python.exe C:/Users/Mayank/PycharmProjects/Emotion-Based-music-player-master/Update_Model.py
Traceback (most recent call last):
  File "C:/Users/Mayank/PycharmProjects/Emotion-Based-music-player-master/Update_Model.py", line 6, in <module>
    fishface=cv2.face.FisherFaceRecognizer_create()
AttributeError: module 'cv2.cv2' has no attribute 'face'

Process finished with exit code 1

**Comment by yashshah2609** [comment]
pip install opencv-contrib-python
try this and then also check for the version of cv2 bcz sometimes in newer versions they change definations.
